# Crossover: ordinal, LocalSearch: None

In [209]:
import numpy as np, random, operator, pandas as pd, matplotlib.pyplot as plt

In [210]:
file_path = "City_Dataset/att48_name.txt"

with open(file_path, "r") as file:
    lines = file.readlines()

nameList = [line.strip() for line in lines]
nameList

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia']

In [211]:
df_data = pd.read_csv("City_Dataset/att48_coordinates.csv", header=None, names=['X', 'Y'])
df_data

       X     Y
0   6734  1453
1   2233    10
2   5530  1424
3    401   841
4   3082  1644
5   7608  4458
6   7573  3716
7   7265  1268
8   6898  1885
9   1112  2049
10  5468  2606
11  5989  2873
12  4706  2674
13  4612  2035
14  6347  2683
15  6107   669
16  7611  5184
17  7462  3590
18  7732  4723
19  5900  3561
20  4483  3369
21  6101  1110
22  5199  2182
23  1633  2809
24  4307  2322
25   675  1006
26  7555  4819
27  7541  3981
28  3177   756
29  7352  4506
30  7545  2801
31  3245  3305
32  6426  3173
33  4608  1198
34    23  2216
35  7248  3779
36  7762  4595
37  7392  2244
38  3484  2829
39  6271  2135
40  4985   140
41  1916  1569
42  7280  4899
43  7509  3239
44    10  2676
45  6807  2993
46  5185  3258
47  3023  1942

In [212]:
class City:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def distance(self, city):
        xDis = abs(self.x - city.x)
        yDis = abs(self.y - city.y)
        distance = np.sqrt((xDis ** 2) + (yDis ** 2))
        return distance
    
    def __repr__(self):
        return "(" + str(self.x) + "," + str(self.y) + ")"

In [213]:
class Fitness:
    def __init__(self, route):
        self.route = route
        self.distance = 0
        self.fitness= 0.0
    
    def routeDistance(self):
        if self.distance ==0:
            pathDistance = 0
            for i in range(0, len(self.route)):
                fromCity = self.route[i]
                toCity = None
                if i + 1 < len(self.route):
                    toCity = self.route[i + 1]
                else:
                    toCity = self.route[0]
                pathDistance += fromCity.distance(toCity)
            self.distance = pathDistance
        return self.distance
    
    def routeFitness(self):
        if self.fitness == 0:
            self.fitness = 1 / float(self.routeDistance())
        return self.fitness

In [214]:
def createRoute(cityList):
    route = random.sample(cityList, len(cityList))
    return route

In [215]:
def initialPopulation(popSize, cityList):
    population = []

    for i in range(0, popSize):
        population.append(createRoute(cityList))
    return population

In [216]:
def rankRoutes(population):
    fitnessResults = {}
    for i in range(0,len(population)):
        fitnessResults[i] = Fitness(population[i]).routeFitness()
    return sorted(fitnessResults.items(), key = operator.itemgetter(1), reverse = True)

In [217]:
def selection(popRanked, eliteSize):
    selectionResults = []
    df = pd.DataFrame(np.array(popRanked), columns=["Index","Fitness"])
    df['cum_sum'] = df.Fitness.cumsum()
    df['cum_perc'] = 100*df.cum_sum/df.Fitness.sum()
    
    for i in range(0, eliteSize):
        selectionResults.append(popRanked[i][0])
    for i in range(0, len(popRanked) - eliteSize):
        pick = 100*random.random()
        for i in range(0, len(popRanked)):
            if pick <= df.iat[i,3]:
                selectionResults.append(popRanked[i][0])
                break
    return selectionResults

In [218]:
def matingPool(population, selectionResults):
    matingpool = []
    for i in range(0, len(selectionResults)):
        index = selectionResults[i]
        matingpool.append(population[index])
    return matingpool

### fix mutation_Permutation Encoding, 서윤님

In [219]:
def breed(parent1, parent2):
    gene_a, gene_b = sorted([random.randint(0, len(parent1) - 1), random.randint(0, len(parent1) - 1)])
    child_p1 = parent1[gene_a:gene_b + 1]
    child_p2 = [item for item in parent2 if item not in child_p1]
    child = parent1[:gene_a] + child_p1 + parent1[gene_b + 1:]
    return child

In [220]:
def breedPopulation(matingpool, elite_size):
    children = []

    for i in range(elite_size):
        children.append(mating_pool[i])

    for i in range(len(mating_pool) - elite_size):
        parent1 = mating_pool[i]
        parent2 = mating_pool[len(mating_pool) - i - 1]
        child = breed(parent1, parent2)
        children.append(child)

    return children

In [221]:
def mutate(individual, mutationRate):
    for swapped in range(len(individual)):
        if(random.random() < mutationRate):
            swapWith = int(random.random() * len(individual))
            
            city1 = individual[swapped]
            city2 = individual[swapWith]
            
            individual[swapped] = city2
            individual[swapWith] = city1
    return individual

In [222]:
def mutatePopulation(population, mutationRate):
    mutatedPop = []
    
    for ind in range(0, len(population)):
        mutatedInd = mutate(population[ind], mutationRate)
        mutatedPop.append(mutatedInd)
    return mutatedPop

In [223]:
def nextGeneration(currentGen, eliteSize, mutationRate):
    popRanked = rankRoutes(currentGen)
    selectionResults = selection(popRanked, eliteSize)
    matingpool = matingPool(currentGen, selectionResults)
    children = breedPopulation(matingpool, eliteSize)
    nextGeneration = mutatePopulation(children, mutationRate)
    return nextGeneration

In [224]:
def geneticAlgorithm(population, popSize, eliteSize, mutationRate, generations):
    pop = initialPopulation(popSize, population)
    print("Initial distance: " + str(1 / rankRoutes(pop)[0][1]))
    
    for i in range(0, generations):
        pop = nextGeneration(pop, eliteSize, mutationRate)
    
    print("Final distance: " + str(1 / rankRoutes(pop)[0][1]))
    bestRouteIndex = rankRoutes(pop)[0][0]
    bestRoute = pop[bestRouteIndex]
    return bestRoute

## Running the genetic algorithm

In [225]:
cityList = []

for i in range(len(df_codata)):
    X, Y = df_codata.values[i]
    cityList.append(City(x=int(X), y=int(Y)))

cityList

[(6734,1453),
 (2233,10),
 (5530,1424),
 (401,841),
 (3082,1644),
 (7608,4458),
 (7573,3716),
 (7265,1268),
 (6898,1885),
 (1112,2049),
 (5468,2606),
 (5989,2873),
 (4706,2674),
 (4612,2035),
 (6347,2683),
 (6107,669),
 (7611,5184),
 (7462,3590),
 (7732,4723),
 (5900,3561),
 (4483,3369),
 (6101,1110),
 (5199,2182),
 (1633,2809),
 (4307,2322),
 (675,1006),
 (7555,4819),
 (7541,3981),
 (3177,756),
 (7352,4506),
 (7545,2801),
 (3245,3305),
 (6426,3173),
 (4608,1198),
 (23,2216),
 (7248,3779),
 (7762,4595),
 (7392,2244),
 (3484,2829),
 (6271,2135),
 (4985,140),
 (1916,1569),
 (7280,4899),
 (7509,3239),
 (10,2676),
 (6807,2993),
 (5185,3258),
 (3023,1942)]

## Plot the improvement

In [226]:
def geneticAlgorithmPlot(population, popSize, eliteSize, mutationRate, generations):
    pop = initialPopulation(popSize, population)
    print("Initial distance: " + str(1 / rankRoutes(pop)[0][1]))
    progress = []
    progress.append(1 / rankRoutes(pop)[0][1])
    
    for i in range(0, generations):
        pop = nextGeneration(pop, eliteSize, mutationRate)
        progress.append(1 / rankRoutes(pop)[0][1])
        
    print("Final distance: " + str(1 / rankRoutes(pop)[0][1]))
    bestRouteIndex = rankRoutes(pop)[0][0]
    bestRoute = pop[bestRouteIndex]

    plt.plot(progress)
    plt.ylabel('Distance')
    plt.xlabel('Generation')
    plt.show()
    return bestRoute

In [227]:
geneticAlgorithmPlot(population=cityList, popSize=100, eliteSize=20, mutationRate=0.01, generations=500)

Initial distance: 134311.29045868502

NameError: name 'elite_size' is not defined

In [ ]:
#Using For optimal 
file_path = "City_Dataset/att48_opttour.txt"
with open(file_path, "r") as file:
    lines = file.readlines()

opt = [int(line.strip()) - 1 for line in lines]
optList = []

for i in range(len(opt)):
            optList.append([df_data.loc[opt[i], "X"], df_data.loc[opt[i], "Y"]])
print(optList)